[DEFAULT]
#banaction = nftables
#banaction_allports = nftables[type=allports]
banaction = nftables[blocktype="counter drop"]
banaction_allports = nftables[type=allports, blocktype="counter drop"]
#banaction_allports = nftables[type=multiport, blocktype="counter drop"]

bantime  = 5m
bantime.maxtime = 48h
bantime.increment = true
bantime.rndtime = 30
bantime.factor = 1
bantime.formula = ban.Time * (1<<(ban.Count if ban.Count<20 else 20)) * banFactor

apache_error_log = /var/log/apache2*/*error.log
apache_access_log = /var/log/apache2*/*access.log

[sshd]
enabled = true
# To use more aggressive sshd modes set filter parameter "mode" in jail.local:
# normal (default), ddos, extra or aggressive (combines all).
# See "tests/files/logs/sshd" or "filter.d/sshd.conf" for usage example and details.
#mode   = normal
mode   = aggressive
port = 0:65535
backend = systemd
journalmatch = _SYSTEMD_UNIT=ssh.service + _COMM=sshd
#logpath = %(sshd_log)s
#backend = %(sshd_backend)s

[synflood]
enabled = false
port = 0:65535
filter = synflood-jau
logpath = /var/log/firewall
banaction = %(banaction_allports)s

[dos]
enabled = false
port = 0:65535
filter = dos-jau
logpath = /var/log/firewall

[dos-syn]
enabled = true
port = 0:65535
filter = dos-syn-jau
logpath = /var/log/firewall

[apache-auth]
enabled = true
port = 0:65535
logpath  = %(apache_error_log)s

[apache-badbots]
enabled = true
port = 0:65535
filter = apache-badbots-jau
logpath  = %(apache_access_log)s
bantime  = 48h
maxretry = 1

[apache-noscript]
enabled = true
port = 0:65535
logpath  = %(apache_error_log)s

[apache-overflows]
enabled = true
port = 0:65535
logpath  = %(apache_error_log)s

[apache-nohome]
enabled = true
port = 0:65535
logpath  = %(apache_error_log)s

[apache-botsearch]
enabled = true
port = 0:65535
logpath  = %(apache_error_log)s

[apache-fakegooglebot]
enabled = true
port = 0:65535
logpath  = %(apache_access_log)s

[sendmail-auth]
enabled = true
port = 0:65535

[sendmail-reject]
enabled = true
port = 0:65535

[dovecot]
enabled = true
port = 0:65535

[sieve]
enabled = true
port = 0:65535
