[DEFAULT]
#banaction = nftables
#banaction_allports = nftables[type=allports]
banaction = nftables[blocktype="counter drop"]
banaction_allports = nftables[type=allports, blocktype="counter drop"]
#banaction_allports = nftables[type=multiport, blocktype="counter drop"]

bantime  = 5m
bantime.maxtime = 48h
bantime.increment = true
bantime.rndtime = 30
bantime.factor = 1
bantime.formula = ban.Time * (1<<(ban.Count if ban.Count<20 else 20)) * banFactor

apache_error_log = /var/log/apache2*/*error.log
apache_access_log = /var/log/apache2*/*access.log

[sshd]
# To use more aggressive sshd modes set filter parameter "mode" in jail.local:
# normal (default), ddos, extra or aggressive (combines all).
# See "tests/files/logs/sshd" or "filter.d/sshd.conf" for usage example and details.
mode   = aggressive
backend = systemd
journalmatch = _SYSTEMD_UNIT=ssh.service + _COMM=sshd
enabled = true
#mode   = normal
#port    = ssh
#logpath = %(sshd_log)s
#backend = %(sshd_backend)s

[synflood]
enabled = false
filter = synflood-jau
logpath = /var/log/firewall
banaction = %(banaction_allports)s

[dos]
enabled = false
filter = dos-jau
logpath = /var/log/firewall

[dos-syn]
enabled = true
filter = dos-syn-jau
logpath = /var/log/firewall

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
# findtime  = 10m

# "maxretry" is the number of failures before a host get banned.
# maxretry = 5
maxretry = 2

[apache-auth]
enabled = true
#backend = systemd
logpath  = %(apache_error_log)s

[apache-badbots]
enabled = true
filter = apache-badbots-jau
port     = http,https
logpath  = %(apache_access_log)s
bantime  = 48h
maxretry = 1

[apache-noscript]
enabled = true
logpath  = %(apache_error_log)s

[apache-overflows]
enabled = true
logpath  = %(apache_error_log)s

[apache-nohome]
enabled = true
logpath  = %(apache_error_log)s

[apache-botsearch]
enabled = true
logpath  = %(apache_error_log)s

[apache-fakegooglebot]
enabled = true
logpath  = %(apache_access_log)s

[sendmail-auth]
enabled = true

[sendmail-reject]
enabled = true

[dovecot]
enabled = true

[sieve]
enabled = true
