# event MPM
# StartServers: initial number of server processes to start
# MinSpareThreads: minimum number of worker threads which are kept spare
# MaxSpareThreads: maximum number of worker threads which are kept spare
# ThreadsPerChild: constant number of worker threads in each server process
# MaxRequestWorkers: maximum number of worker threads
# MaxConnectionsPerChild: maximum number of requests a server process serves

StartServers            5
# MinSpareThreads to equal 50% of MaxRequestWorkers.
MinSpareThreads         200
# MaxSpareThreads >= MinSpareThreads + ThreadsPerChild
MaxSpareThreads         250

# ServerLimit 16 (default)
# ThreadsPerChild 25 (default)
# MaxRequestWorkers = ServerLimit * ThreadsPerChild = 400
# MaxRequestWorkers       400
#
# Default
#ServerLimit 16
#ThreadLimit     25
#ThreadsPerChild 25
#MaxRequestWorkers 400

#
# Higher
ServerLimit 24
ThreadLimit     25
ThreadsPerChild 25
MaxRequestWorkers 600
#
# Higher
#ServerLimit 24
#ThreadLimit     32
#ThreadsPerChild 32
#MaxRequestWorkers 768
#
# Higher
#ServerLimit 28
#ThreadLimit     32
#ThreadsPerChild 32
#MaxRequestWorkers 896

#ServerLimit 32
#ThreadLimit     32
#ThreadsPerChild 32
#MaxRequestWorkers 1000

#MaxConnectionsPerChild  0
#(Optional - Less for more buggy processes to manage memory leaks)
MaxConnectionsPerChild   10000
#MaxConnectionsPerChild   1000

