#! /bin/sh

#set -x

action=$1
shift

#
#* Single end device with untrusted inet connection
#

ETH_EXTERN=eth0
IP_EXTERN_SELF=$( /sbin/ip -o -f inet6 addr show dev $ETH_EXTERN scope global | awk ' { print $4;  } ' )
IP_EXTERN_GW=$( /sbin/ip -o -f inet6 route show dev $ETH_EXTERN | grep default | awk ' { print $3;  } ' )

##
##

IPTABLES=/sbin/ip6tables

if [ "$action" != "start" -a "$action" != "stop" -a "$action" != "restart" ] ; then
        echo usage $0 \( start \| stop \| restart \)
        echo

elif [ "$action" = "restart" ] ; then
        $0 stop
        $0 start

elif [ "$action" = "stop" ] ; then

        echo "IPTABLES rules down"

        $IPTABLES -F acl_external_input
        $IPTABLES -F dos_limiter
        $IPTABLES -F syn_flood
        $IPTABLES -F acl_srv_connect
        $IPTABLES -F acl_srv_web
        $IPTABLES -F acl_srv_shared
        $IPTABLES -F acl_srv_email
        $IPTABLES -F acl_srv_login_sec
        $IPTABLES -F drop_icmp
        $IPTABLES -F drop_syn_ip
        $IPTABLES -F drop_syn_gl
        $IPTABLES -F drop_dos
        $IPTABLES -F rejc_dos
        $IPTABLES -F INPUT
        $IPTABLES -F FORWARD
        $IPTABLES -F

        $IPTABLES -X acl_external_input
        $IPTABLES -X dos_limiter
        $IPTABLES -X syn_flood
        $IPTABLES -X acl_srv_connect
        $IPTABLES -X acl_srv_web
        $IPTABLES -X acl_srv_shared
        $IPTABLES -X acl_srv_email
        $IPTABLES -X acl_srv_login_sec
        $IPTABLES -X drop_icmp
        $IPTABLES -X drop_syn_ip
        $IPTABLES -X drop_syn_gl
        $IPTABLES -X drop_dos
        $IPTABLES -X rejc_dos
        $IPTABLES -X

        $IPTABLES -P INPUT   ACCEPT
        $IPTABLES -P FORWARD ACCEPT

elif [ "$action" = "start" ] ; then

        echo "IPTABLES rules up"

        # Anti-spoofing
        #
        # Since we don't have any asymmetric routing,
        # we can simply turn on anti-spoofing for all interfaces.
        #
        #for f in /proc/sys/net/ipv4/conf/*ppp*/rp_filter; do echo 1 > $f; done

        $IPTABLES -P INPUT   DROP

        $IPTABLES -N acl_external_input
        $IPTABLES -N dos_limiter
        $IPTABLES -N syn_flood
        $IPTABLES -N acl_srv_connect
        $IPTABLES -N acl_srv_web
        $IPTABLES -N acl_srv_shared
        $IPTABLES -N acl_srv_email
        $IPTABLES -N acl_srv_login_sec
        $IPTABLES -N drop_icmp
        $IPTABLES -N drop_syn_ip
        $IPTABLES -N drop_syn_gl
        $IPTABLES -N drop_dos
        $IPTABLES -N rejc_dos

        ###################################################################
        ###################################################################
        #

        # INPUT -> user chains
        #
        # Unfortunately, we only know (in the FORWARD chain) the outgoing interface.
        # Thus, to figure out what interface the packet came in on,
        # we use the source address (the anti-spoofing prevents address faking).
        #
        # Note that we log anything which doesn't match any of these (obviously, this should never happen).
        #

        #
        # INPUT Allow FIREWALL itself !
        #
        $IPTABLES -p all -A INPUT  -i $ETH_EXTERN         -s $IP_EXTERN_SELF                   -j ACCEPT
        $IPTABLES -p all -A INPUT  -i lo                                                       -j ACCEPT

        $IPTABLES -p all -A INPUT  -i $ETH_EXTERN                                              -j acl_external_input

        #$IPTABLES -p tcp -A INPUT  -i $ETH_EXTERN  --tcp-flags ACK ACK                         -j LOG \
        #             --log-level debug --log-prefix "FW6-IN: ack "
        $IPTABLES -p tcp -A INPUT  -i $ETH_EXTERN  --tcp-flags ACK ACK                         -j ACCEPT

        $IPTABLES -p all -A INPUT  -i $ETH_EXTERN   -j LOG --log-level debug --log-prefix "FW6-IN: rej acl_ext input "
        $IPTABLES -p all -A INPUT  -i $ETH_EXTERN                                              -j REJECT

        #
        # INPUT Log & Reject any
        #
        $IPTABLES -p all -A INPUT                        -j LOG --log-level debug --log-prefix "FW6-IN: rej ANY input "
        $IPTABLES -p all -A INPUT                                                              -j REJECT

        #
        ###################################################################
        ###################################################################
        ###################################################################
        #

        # FORWARD -> user chains
        #

        #
        # FORWARD Allow FIREWALL itself !
        #
        $IPTABLES -p all -A FORWARD  -i $ETH_EXTERN         -s $IP_EXTERN_SELF                 -j ACCEPT
        $IPTABLES -p all -A FORWARD  -i lo                                                     -j ACCEPT

        $IPTABLES -p all -A FORWARD  -i $ETH_EXTERN                                            -j acl_external_input
        $IPTABLES -p all -A FORWARD  -i $ETH_EXTERN   -j LOG --log-level debug --log-prefix "FW6-FWD: rej acl_ext input "
        $IPTABLES -p all -A FORWARD  -i $ETH_EXTERN                                            -j REJECT

        #
        # FORWARD Log & Reject any
        #
        $IPTABLES -p all -A FORWARD    -j LOG --log-level debug --log-prefix "FW6-FWD: rej ANY input "
        $IPTABLES -p all -A FORWARD                                                            -j REJECT

        #
        #
        #########################################################################################################################
        #########################################################################################################################
        #########################################################################################################################
        #
        # acl_extern_
        #
        $IPTABLES -p all -A acl_external_input                                                 -j dos_limiter

        # Protocol rules
        $IPTABLES -p all -A acl_external_input                                                 -j acl_srv_connect     # includes: allow to answer ..
        $IPTABLES -p all -A acl_external_input                                                 -j acl_srv_login_sec
        $IPTABLES -p all -A acl_external_input                                                 -j acl_srv_web
        $IPTABLES -p all -A acl_external_input                                                 -j acl_srv_shared
        $IPTABLES -p all -A acl_external_input                                                 -j acl_srv_email

        # --syn == "--tcp-flags SYN,RST,ACK SYN"
        #$IPTABLES -p tcp -A acl_external_input        ! --syn -j LOG --log-level debug --log-prefix "FW6-Ext: rej INET !syn "
        #$IPTABLES -p tcp -A acl_external_input        ! --syn                                 -j REJECT
        #$IPTABLES -p all -A acl_external_input -m state ! --state ESTABLISHED,RELATED   -j LOG --log-level debug --log-prefix "FW6-Ext: rej INET !resp "
        #$IPTABLES -p all -A acl_external_input -m state ! --state ESTABLISHED,RELATED         -j REJECT

        #########################################################################################################################
        #########################################################################################################################
        #########################################################################################################################
        #
        # dos_limiter, syn_flood
        #

        # Monitor
        # ip6tables -L dos_limiter -n -v
        # ip6tables -L syn_flood -n -v
        #
        # echo -n "ns 443         " ; netstat -tuna | grep :443 | wc -l
        # echo -n "ss established " ; ss -tan state established | wc -l
        # echo -n "ns syn         " ; netstat -tuna | grep SYN | wc -l
        # echo -n "ss syn-recv    " ; ss -tan state syn-recv | wc -l
        #
        # cat /proc/net/ip6t_hashlimit/ssh-limit
        # cat /proc/net/ip6t_hashlimit/http-limit
        # cat /proc/net/ip6t_hashlimit/https-limit
        #

        $IPTABLES -p all -A drop_icmp -m limit --limit 1/s -j LOG --log-level debug --log-prefix "FW6-ICMP: drop "
        $IPTABLES -p all -A drop_icmp -j DROP

        $IPTABLES -p all -A drop_syn_ip -m limit --limit 1/s -j LOG --log-level debug --log-prefix "FW6-SYN-IP: drop "
        $IPTABLES -p all -A drop_syn_ip -j DROP
        $IPTABLES -p all -A drop_syn_gl -m limit --limit 1/s -j LOG --log-level debug --log-prefix "FW6-SYN-GL: drop "
        $IPTABLES -p all -A drop_syn_gl -j DROP

        $IPTABLES -p all -A drop_dos -m limit --limit 1/s -j LOG --log-level debug --log-prefix "FW6-DOS: drop "
        $IPTABLES -p all -A drop_dos -j DROP

        $IPTABLES -p all -A rejc_dos -m limit --limit 1/s -j LOG --log-level debug --log-prefix "FW6-DOS: reject "
        $IPTABLES -p all -A rejc_dos -j REJECT

        # ICMP
        #
        # Allow fragments (second etc. parts of a huge packet ..)
        # Allow icmpv6 notification: 3/4 destination-unreachable/fragmentation-needed
        #
        # ATTENTION .. can be anything (ICMP), but the very 1st will be filtered ok !
        #
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type echo-request -m limit --limit 5/s --limit-burst 10 -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type echo-reply                                         -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type destination-unreachable                            -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type packet-too-big                                     -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type time-exceeded                                      -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type parameter-problem                                  -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type neighbour-solicitation                             -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type neighbour-advertisement                            -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type router-solicitation                                -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6 --icmpv6-type router-advertisement                               -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6                            -m limit --limit 5/s --limit-burst 10 -j ACCEPT
        $IPTABLES  -A dos_limiter   -p icmpv6                                                                  -j drop_icmp

        # Limit SYN packets to an average of 50 per second, with a burst of 100
        $IPTABLES -A dos_limiter    -p tcp --syn                          -j syn_flood

        #
        # Per-IP rate stats new connections (SYN)
        $IPTABLES -A syn_flood -m hashlimit --hashlimit-name synflood1 --hashlimit-mode srcip \
                  --hashlimit-upto   1/sec --hashlimit-burst  3 --hashlimit-htable-expire 60000 -j RETURN

        $IPTABLES -A syn_flood -m hashlimit --hashlimit-name synflood3 --hashlimit-mode srcip \
                  --hashlimit-upto   3/sec --hashlimit-burst  6 --hashlimit-htable-expire 60000 -j RETURN

        # Per-IP rate limiting new connections (SYN)
        $IPTABLES -A syn_flood -m hashlimit --hashlimit-name synflood --hashlimit-mode srcip \
                  --hashlimit-above  6/sec --hashlimit-burst 12 --hashlimit-htable-expire 60000 -j drop_syn_ip
        #
        # Global SYN rate limit (last resort)
        # $IPTABLES -A syn_flood  -m limit --limit 1200/s --limit-burst 2000 -j RETURN
        # $IPTABLES -A syn_flood                                            -j drop_syn_gl
        $IPTABLES -A syn_flood                                            -j RETURN

        # Per-IP rate limiting for new SSH connections
        $IPTABLES -A dos_limiter -p tcp --dport 22 \
                  -m conntrack --ctstate NEW \
                  -m hashlimit \
                  --hashlimit-name ssh-limit --hashlimit-mode srcip \
                  --hashlimit-above 30/min --hashlimit-burst 50 \
                  --hashlimit-htable-expire 60000 \
                  -j drop_dos

        # Rate limit new HTTP connections per IP
        $IPTABLES -A dos_limiter -p tcp --dport 80 \
                  -m conntrack --ctstate NEW \
                  -m hashlimit \
                  --hashlimit-name http-limit --hashlimit-mode srcip \
                  --hashlimit-above 5/s --hashlimit-burst 10 \
                  --hashlimit-htable-expire 60000 \
                  -j drop_dos

        $IPTABLES -A dos_limiter -p tcp --dport 443 \
                  -m conntrack --ctstate NEW \
                  -m hashlimit \
                  --hashlimit-name https-limit --hashlimit-mode srcip \
                  --hashlimit-above 5/s --hashlimit-burst 10 \
                  --hashlimit-htable-expire 60000 \
                  -j drop_dos

        # Limit concurrent SSH connections per IP
        $IPTABLES -A dos_limiter -p tcp --syn --dport 22 \
                  -m connlimit --connlimit-above 30 -j rejc_dos

        # Limit concurrent HTTP connections per IP
        $IPTABLES -A dos_limiter -p tcp --syn --dport 80 \
                  -m connlimit --connlimit-above 5 -j rejc_dos
        $IPTABLES -A dos_limiter -p tcp --syn --dport 443 \
                  -m connlimit --connlimit-above 5 -j rejc_dos

        $IPTABLES -A dos_limiter                -j RETURN

        #
        #########################################################################################################################
        #########################################################################################################################
        #########################################################################################################################
        #
        # INPUT Allow acl_srv_shared
        #
        # FTP, SAMBA, GNUnet clients
        #

        # ANONYMOUS FTP
        #
        #$IPTABLES -p tcp -A acl_srv_shared        --dport ftp-data:ftp                        -j ACCEPT
        #$IPTABLES -p udp -A acl_srv_shared        --dport ftp-data:ftp                        -j ACCEPT

        $IPTABLES -p tcp -A acl_srv_shared        --dport git                                  -j ACCEPT
        $IPTABLES -p udp -A acl_srv_shared        --dport git                                  -j ACCEPT

        #
        #
        #########################################################################################################################
        #
        # INPUT Allow acl_srv_login_sec
        #
        # SSH
        #

        # SSH
        #
        #$IPTABLES -p tcp -A acl_srv_login_sec        --dport ssh                              -j LOG --log-level debug --log-prefix "FW6-ACL_SSH: "
        $IPTABLES -p tcp -A acl_srv_login_sec        --dport ssh                               -j ACCEPT
        $IPTABLES -p udp -A acl_srv_login_sec        --dport ssh                               -j ACCEPT

        #
        #
        #########################################################################################################################
        #
        # INPUT Allow acl_srv_email
        #
        # POP3s, SMTP
        #

        # IMAPs
        #
        $IPTABLES -p tcp -A acl_srv_email        --dport imaps                                 -j ACCEPT

        # POP3s
        #
        $IPTABLES -p tcp -A acl_srv_email        --dport pop3s                                 -j ACCEPT

        # ident
        #
        $IPTABLES -p tcp -A acl_srv_email        --dport ident                                 -j ACCEPT

        # SMTPs
        #
        $IPTABLES -p tcp -A acl_srv_email        --dport smtp                                  -j ACCEPT
        $IPTABLES -p tcp -A acl_srv_email        --dport smtps                                 -j ACCEPT
        $IPTABLES -p tcp -A acl_srv_email        --dport sieve                                 -j ACCEPT

        #
        #########################################################################################################################
        #
        # INPUT Allow acl_srv_web
        #
        # HTTP, NTP
        #

        # HTTP
        #
        $IPTABLES -p tcp -A acl_srv_web        --dport http                                    -j ACCEPT
        $IPTABLES -p tcp -A acl_srv_web        --dport https                                   -j ACCEPT
        #$IPTABLES -p tcp -A acl_srv_web        --dport http-alt                               -j ACCEPT
        #$IPTABLES -p tcp -A acl_srv_web        --dport webcache                               -j ACCEPT
        #$IPTABLES -p tcp -A acl_srv_web        --dport squid                                  -j ACCEPT

        #
        #
        #########################################################################################################################
        #
        # INPUT Allow acl_srv_connect
        #
        # ICMP, NTP, DHCP, DNS, ANSWER
        #

        # IPSEC
        #
        #$IPTABLES -p ah  -A acl_srv_connect                                                    -j ACCEPT
        $IPTABLES -p esp -A acl_srv_connect                                                    -j ACCEPT

        # DHCP .. TFTP
        #
        $IPTABLES -p udp -A acl_srv_connect -i $ETH_EXTERN --dport mdns        -s $IP_EXTERN_SELF  -j ACCEPT #
        $IPTABLES -p udp -A acl_srv_connect -i $ETH_EXTERN --dport bootps:tftp -s $IP_EXTERN_GW    -j ACCEPT #
        $IPTABLES -p tcp -A acl_srv_connect -i $ETH_EXTERN --dport bootps:69   -s $IP_EXTERN_GW    -j ACCEPT #

        # DNS
        #
        # $IPTABLES -p tcp -A acl_srv_connect        --dport mdns                              -j ACCEPT
        # $IPTABLES -p udp -A acl_srv_connect        --dport mdns                              -j ACCEPT
        # $IPTABLES -p tcp -A acl_srv_connect        --dport domain                            -j ACCEPT
        # $IPTABLES -p udp -A acl_srv_connect        --dport domain                            -j ACCEPT
        # $IPTABLES -p tcp -A acl_srv_connect        --dport netbios-ns:netbios-ssn            -j ACCEPT
        # $IPTABLES -p udp -A acl_srv_connect        --dport netbios-ns:netbios-ssn            -j ACCEPT

        # iperf
        #
        #$IPTABLES -p tcp  -A acl_srv_connect         --dport 5001                              -j ACCEPT
        #$IPTABLES -p udp  -A acl_srv_connect         --dport 5001                              -j ACCEPT

        #
        # acl_srv_connect Allow * to answer,
        # only for known connections - no new unknown ones !
        #
        $IPTABLES -p all  -A acl_srv_connect          -m state   --state ESTABLISHED,RELATED   -j ACCEPT

        #
        #
        #########################################################################################################################
fi

